apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-admin
  namespace: malaby-dev
  labels:
    app: frontend-admin
    app.kubernetes.io/part-of: malaby
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-admin
  template:
    metadata:
      labels:
        app: frontend-admin
        app.kubernetes.io/part-of: malaby
    spec:
      containers:
        - name: nginx
          image: 192.168.1.8:30082/malaby/frontend-admin@sha256:844e8dc0e0c954a4daee936da3ae9996ee4f21719a9199b29a7b14af241f347b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
  namespace: malaby-dev
  labels:
    app: frontend-admin
    app.kubernetes.io/part-of: malaby
spec:
  selector:
    app: frontend-admin
  ports:
    - name: http
      port: 80
      targetPort: 80
