apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: malaby-api
  namespace: malaby-dev
  labels:
    app.kubernetes.io/part-of: malaby
    release: prometheus
spec:
  namespaceSelector:
    matchNames: [malaby-dev]
  selector:
    matchLabels: { app: api }
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
