#!/usr/bin/env bash
# Commit-msg hook: enforce Conventional Commits.
# Usage (pre-commit commit-msg stage): commit-msg-conventional.sh <commit-msg-file>
set -uo pipefail
msg_file="${1:?commit message file required}"
first_line="$(head -n1 "$msg_file")"

# Allow merge/revert/fixup/squash autogenerated commits.
case "$first_line" in
  Merge*|Revert*|fixup!*|squash!*) exit 0 ;;
esac

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|security)(\([a-z0-9._/-]+\))?!?: .{1,}'
if ! [[ "$first_line" =~ $pattern ]]; then
  echo "Invalid commit message: $first_line"
  echo "Use Conventional Commits, e.g. 'feat(api): add JWT admin auth'."
  exit 1
fi
echo "commit-msg: conventional format OK."
