apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets-eso
  namespace: malaby-dev
  labels:
    app.kubernetes.io/part-of: malaby
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: api-secrets-eso
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: dev/api
        property: JWT_SECRET
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: dev/api
        property: ADMIN_USERNAME
    - secretKey: ADMIN_PASSWORD_HASH
      remoteRef:
        key: dev/api
        property: ADMIN_PASSWORD_HASH
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: dev/api
        property: ADMIN_PASSWORD
    - secretKey: CORS_ORIGIN
      remoteRef:
        key: dev/api
        property: CORS_ORIGIN
