apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secrets-eso
  namespace: malaby-dev
  labels:
    app.kubernetes.io/part-of: malaby
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: mongodb-secrets-eso
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dev/mongodb
