apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: malaby-dev
  labels:
    app.kubernetes.io/part-of: malaby
    app.kubernetes.io/component: secrets
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "malaby"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "malaby-dev"
          serviceAccountRef:
            name: "eso-vault"
