apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-vault
  namespace: malaby-dev
  labels:
    app.kubernetes.io/part-of: malaby
    app.kubernetes.io/component: secrets
automountServiceAccountToken: false
